apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-app
  namespace: resume
  labels:
    app: resume-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume-app
  template:
    metadata:
      namespace: resume
      labels:
        app: resume-app
    spec:
      containers:
      - name: resume-pod
        image: litespeedtech/openlitespeed
        ports:
        - containerPort: 80
        volumeMounts:
            - mountPath: /var/www/vhosts/localhost/html
              name: web
      restartPolicy: Always
      volumes:
      - name: web
        nfs:
          path: /mnt/mainPool/cluster/resume
          server: 192.168.50.51
---
apiVersion: v1
kind: Service
metadata:
  name: resume-app-service
  namespace: resume
spec:
  selector:
    app: resume-app
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: LoadBalancer
