piVersion: v1
kind: Namespace
metadata:
  name: resume
  labels:
    name: resume
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-app
  namespace: resume
  labels:
    app: resume-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume-app
  template:
    metadata:
      namespace: resume
      labels:
        app: resume-app
    spec:
      containers:
      - name: resume-pod
        image: litespeedtech/openlitespeed
        ports:
        - containerPort: 80
        volumeMounts:
            - mountPath: /var/www/vhosts/localhost/html
              name: web
      restartPolicy: Always
      volumes:
      - name: web
        nfs:
          path: /mnt/mainPool/cluster/resume
          server: 192.168.50.51
---
apiVersion: v1
kind: Service
metadata:
  name: resume-service
  namespace: resume
spec:
  selector:
    app: resume-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: resume
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
#   nginx.ingress.kubernetes.io/ssl-redirect: "false"
  labels:
    app: resume-ingress
  name: resume-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: ameeuwsen.com
      http:
        paths:
          - backend:
              service:
                name: resume-service
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - ameeuwsen.com
      secretName: ameeuwsen-tls-cert
