apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app-deployment
  namespace: resume
  labels:
    app: php-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      namespace: resume
      labels:
        app: php-app
    spec:
      containers:
      - name: php-fpm
        image: bitnami/php-fpm:latest
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Services
metadata:
  namespace: resume
  name: php-app-service
spec:
  selector:
    app: php-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  type: LoadBalancer
